"""Finalize data models based on full app logic

Revision ID: b65116016ff9
Revises: ceeeca26420f
Create Date: 2025-07-06 08:35:37.998529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65116016ff9'
down_revision = 'ceeeca26420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('user')
    op.drop_table('expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('particulars', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('debit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('checkin_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('checkout_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('on_offline', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('booking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cleaning_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('platform_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey'))
    )
    # ### end Alembic commands ###
