"""Remove unique constraint from booking number

Revision ID: ceeeca26420f
Revises: d8a43f6c3525
Create Date: 2025-07-05 23:53:20.865778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeeca26420f'
down_revision = 'd8a43f6c3525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('booking_booking_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('booking_booking_number_key'), ['booking_number'], postgresql_nulls_not_distinct=False)

    op.drop_table('user')
    # ### end Alembic commands ###
