"""Initial migration with User, Booking, and Expense tables.

Revision ID: d8a43f6c3525
Revises: 
Create Date: 2025-07-05 19:34:50.358268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a43f6c3525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('on_offline', sa.String(length=50), nullable=True),
    sa.Column('booking_number', sa.String(length=100), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cleaning_fee', sa.Float(), nullable=True),
    sa.Column('platform_charge', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_number')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('particulars', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('booking')
    # ### end Alembic commands ###
